blog/urls.py
from django.urls import path
from blog.views import ListPostsView, DetailPostView

app_name = "posts"

urlpatterns = [
    path('', ListPostsView.as_view(), name='list'),
    path('post/<int:pk>/', DetailPostView.as_view(), name='detail'),
]

core/urls.py
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from tinymce.models import HTMLField

# Create your models here.
class Posts(models.Model):
    title = models.CharField(
        "Titulo", max_length=255, null=False, blank=False
    )
    image = models.ImageField(
        "Imagem", upload_to="images/blog/", null=True, blank=True
    )
    content = HTMLField("Conteúdo", null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.title}"
    
    class Meta:
        ordering = ["created_at"]
        verbose_name = "post"
        verbose_name_plural = "posts"

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from blog.models import Posts


class ListPostsView(ListView):
    model = Posts
    template_name = "list.html"
    context_object_name = "posts"
    paginate_by = 10


class DetailPostView(DetailView):
    model = Posts
    template_name = 'detail.html'
    context_object_name = 'post'

blog/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/blog/styles.css' %}">
{% endblock %}

<main>
    {% block content %}
        <div class="container-posts">
            <div class="card-post">
                <h1>{{ post.title }}</h1>
                {% if post.image %}
                    <div class="image-post">
                        <img src="{{ post.image.url }}" alt="image post">
                    </div>
                {% endif %}
                <p>{{ post.content|safe }}</p>
            </div>
        </div>
    {% endblock %}
</main>

blog/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/blog/styles.css' %}">
{% endblock %}

<main>
    {% block content %}
        <div class="container-posts">
            {% for post in posts %}
                <a class="card-post" href="{% url 'posts:detail' post.pk %}">
                    <div class="card-post-title">
                        <h1>{{ post.title }}</h1>
                    </div>
                    <div class="card-post-content">
                        {% if post.image %}
                            <div class="text">
                                <p>{{ post.content|safe|truncatewords:70 }}</p>
                                <img src="{{ post.image.url }}" alt="post-image">
                            </div>
                        {% else %}
                            <div class="text">
                                <p>{{ post.content|safe|truncatewords:90 }}</p>
                            </div>
                        {% endif %}
                    </div>
                </a>
            {% endfor %}
            <div class="pagination">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; Primeira</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}

                <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Próxima</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">Última &raquo;</a>
                {% endif %}
            </div>
        </div>
    {% endblock %}
</main>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/header/styles.css' %}">
    
    {% block styles %}{% endblock %}

    <title>{% block title %} {% endblock %}</title>

</head>
<body>

    {% include 'header.html' %}

    <main>
        {% block content %} {% endblock %}
    </main>

    {% block scripts %}{% endblock %}

</body>
</html>

templates/header.html
{% load static %}
<header>
    <div class="header-title">
        <h1>Blog</h1>
    </div>
</header>